[package]
name = "frontend"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { path = "../app", default-features = false, features = [
  "hydrate",
], optional = true }
leptos = { workspace = true, features = ["hydrate"], optional = true }

console_error_panic_hook.workspace = true
console_log.workspace = true
log.workspace = true
wasm-bindgen.workspace = true

[features]
default = []
hydrate = ["app", "leptos/hydrate"]
ssr = []
