[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 1


[unstable]
codegen-backend = true

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Zcodegen-backend=cranelift",
    "-C",
    "link-arg=-fuse-ld=/usr/bin/mold"
]
linker = "clang"