[toolchain]
channel = "nightly-2025-11-24"
components = [
  "cargo",
  "clippy",
  "rust-analyzer",
  "rust-std",
  "rustc-codegen-cranelift-preview",
  "rustfmt",
]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
profile = "default"
