[toolchain]
channel = "nightly-2025-05-04"
components = [
  "rustfmt",
  "rust-analyzer",
  "cargo",
  "clippy",
  "rust-std",      # Test
]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
profile = "default"
